// <auto-generated />
namespace Website_EcommerceShoe_ASPNETMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class zzzzzzzz : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(zzzzzzzz));
        
        string IMigrationMetadata.Id
        {
            get { return "202303241032132_zzzzzzzz"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
